### DISCUSSION TITLE
About style of the Sidebar content

### DISCUSSION THREAD

**Discussion by AnZeng00** [vikramlearning/blazorbootstrap#180] [Q&A]
Hi,
I want to modify the style of the sidebar item. 
![sidebar only css](https://user-images.githubusercontent.com/52019144/230841997-d141556a-d73b-4f67-a9fd-fb622a0d3907.png)
Could you please tell me the way?

**Comment by gvreddy04** [comment]
@AnZeng00 Thank you for trying the BlazorBootstrap components.

Yes, you can customize the sidebar colors.

Add the below CSS variables to the application CSS file and update the CSS variables according to your colors. It will work.

```css
<style>
        :root {
            --bb-sidebar-width: 270px;
            --bb-sidebar-collapsed-width: 50px;
            --bb-sidebar-background-color: rgba(234, 234, 234, 1);
            --bb-sidebar-top-row-background-color: rgba(0,0,0,0.08);
            --bb-sidebar-top-row-border-color: rgb(194,192,192);
            --bb-sidebar-title-text-color: rgb(0,0,0);
            --bb-sidebar-brand-icon-color: #6f42c1;
            --bb-sidebar-brand-image-width: 24px;
            --bb-sidebar-brand-image-height: 24px;
            --bb-sidebar-title-badge-text-color: rgb(255,255,255);
            --bb-sidebar-title-badge-background-color: rgba(25,135,84,var(--bs-bg-opacity,1));
            --bb-sidebar-navbar-toggler-icon-color: rgb(0,0,0);
            --bb-sidebar-navbar-toggler-background-color: rgba(0,0,0,0.08);
            --bb-sidebar-content-border-color: rgb(194,192,192);
            --bb-sidebar-nav-item-text-color: rgba(0,0,0,0.9);
            --bb-sidebar-nav-item-text-active-color-rgb: 0,0,0;
            --bb-sidebar-nav-item-text-hover-color: rgba(var(--bb-sidebar-nav-item-text-active-color-rgb),0.9);
            --bb-sidebar-nav-item-text-active-color: rgba(var(--bb-sidebar-nav-item-text-active-color-rgb),0.9);
            --bb-sidebar-nav-item-background-hover-color: rgba(var(--bb-sidebar-nav-item-text-active-color-rgb),0.08);
            --bb-sidebar-nav-item-group-background-color: rgba(var(--bb-sidebar-nav-item-text-active-color-rgb),0.08);
        }
</style>
```

## Refer Customize sidebar: 
- Docs: https://getblazorbootstrap.com/docs/components/sidebar#customize-sidebar
- Demos: https://demos.blazorbootstrap.com/sidebar#customize-sidebar

![image](https://user-images.githubusercontent.com/2337067/230899389-c31ecc77-d4bb-407c-ad5c-ffb127223d4b.png)
