### DISCUSSION TITLE
Sidebar Top-row height

### DISCUSSION THREAD

**Discussion by striker313131** [vikramlearning/blazorbootstrap#723] [General]
Hello maybe I missed something but is there a way to customize the height of the Top-row (by default 3.5rem). 

Thanks!

**Comment by gvreddy04** [comment]
@striker313131 Thank you for using BlazorBootstrap. Override the height.

Example: 

```css
.bb-sidebar-top-row {
    height: 5.5rem !important;
}
```
