### ISSUE TITLE
How to override the sidebar item's font size and item's height?

### ISSUE THREAD

**Issue by AnZeng00** [vikramlearning/blazorbootstrap#311]
I want to increase the size of sidebar menu text and increase the height of the sidebar menu item. But I don't know How to do that. Can Someone tell me?

**Comment by gvreddy04** [comment]
@AnZeng00 Use the following CSS to override the font-size and item height.

```css
.bb-sidebar .nav-item {
    line-height: 3rem;
    font-size: 1.5rem;
}
```

**Before:**

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/efd098dd-c797-49ea-9fae-d8f4cf1d65f9)

**After:**

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/a10713e7-7da2-4b9d-9b96-2501d6152db4)
