### ISSUE TITLE
Grid row selection - highlight the row

### ISSUE THREAD

**Issue by vasuamics** [vikramlearning/blazorbootstrap#769]
**Describe the bug**
Is it possible to highlight an entire row when selected and to use up and down arrow keys to select a row?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - .NET Version: [e.g. .NET 6, .NET 7, .NET 8]
 - BlazorBootstrap: [e.g. 2.0.0, 2.1.0, 2.2.0]
 - Blazor WebAssembly / Server: [e.g. WebAssembly, Server]
 - Blazor Interactive Render Mode: [e.g. Auto, Server, WebAssembly, None]
 - Blazor Interactivity Location: [e.g. Global, Per page/component]

**Sample code**
Sample code to reproduce the issue.

**GitHub repo**
GitHub repo with minimal code to reproduce the issue.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gvreddy04** [comment]
@vasuamics Highlighting rows upon selection can be done. We will do it as an enhancement. However, you cannot currently select rows using the up/down keys.

**Comment by gvreddy04** [comment]
@vasuamics In the meantime, you can use the following CSS:

## Example 1

**Sample CSS:**

```css
.bb-table tr:has(input[type=checkbox]:checked){
    background-color: red;
}
```

**Screenshot:**

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/01524b60-0b7e-4cba-a73c-bd681abf1242)


## Exmaple 2:

**Sample CSS:**

```css
.bb-table tr:has(input[type=checkbox]:checked){
    background-color: rgba(0,0,0,0.0725);
}
```

**Screenshot:**

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/1a4c4737-aac2-4592-8b38-a798621aa6d1)
